# Generated by Django 3.2 on 2022-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncov',
            name='leijiquezhen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncov',
            name='leijisiwang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ncov',
            name='xinzengquezhen',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ncov',
            name='xinzengyisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='ncov',
            table='ncov',
        ),
    ]
